### ISSUE TITLE
Automatically choosing small feeds

### ISSUE THREAD

**Issue by bunsenPburner** [1200wd/bitcoinlib#105]
Ignore. Found that the issues were coming from failed transactions being stored in the database. Once removed, everything worked again. Still don't know why transactions failed but looking into it.

**Comment by bunsenPburner** [comment]
It appears that those links no longer show the attempted transaction. I tried to run a scan but kept receiving this error

```
Traceback (most recent call last):
  File "testing.py", line 7, in <module>
    w.scan()
  File "/usr/local/lib/python3.6/dist-packages/bitcoinlib/wallets.py", line 1771, in scan
    t.block_height = new_t.block_height
AttributeError: 'bool' object has no attribute 'block_height'
```

I removed the 2 attempted transactions from the database and it appears to be working now. Still unsure why it didn't go through but balance and UTXOs appear correct.
