### ISSUE TITLE
Option to use encrypted sqlite database

### ISSUE THREAD

**Issue by rhamnett** [1200wd/bitcoinlib#170]
What are your thoughts on using an encrypted database? I am thinking about adapting the source to support something like https://charlesleifer.com/blog/encrypted-sqlite-databases-with-python-and-sqlcipher/

@mccwdev  Can you please commend and give me your thoughts/suggestions before I start work?

Thanks

**Comment by mccwdev** [comment]
I've recently tested and added support for SQLCipher, see https://bitcoinlib.readthedocs.io/en/0.5.2/source/_static/manuals.sqlcipher.html

I see the documentation is not correctly updated, so this page is not in the main manual yet.

Let me know you thoughts and experiences

**Comment by rhamnett** [comment]
Nice thanks!

I tried with python3.8 and successfully built and installed pysqlcipher3 but when running the script for some reason seems to be looking for pysqlcipher not pysqlcipher3. Would you be able to advise?

```
python3.8 test.py
Traceback (most recent call last):
  File "/home/ec2-user/environment/test-tester/sqlalchemy/dialects/sqlite/pysqlcipher.py", line 99, in dbapi
    from pysqlcipher3 import dbapi2 as sqlcipher
  File "/home/ec2-user/environment/test-tester/pysqlcipher3/dbapi2.py", line 33, in <module>
    from pysqlcipher3._sqlite3 import *
ImportError: libsqlcipher.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    wlt = Wallet.create('bcltestwlt4', network='bitcoinlib_test', db_uri=db_uri)
  File "/home/ec2-user/environment/test-tester/bitcoinlib/wallets.py", line 1235, in create
    hdpm = cls._create(name, key, owner=owner, network=network, account_id=account_id, purpose=purpose,
  File "/home/ec2-user/environment/test-tester/bitcoinlib/wallets.py", line 977, in _create
    session = Db(db_uri=db_uri).session
  File "/home/ec2-user/environment/test-tester/bitcoinlib/db.py", line 67, in __init__
    self.engine = create_engine(db_uri, isolation_level='READ UNCOMMITTED')
  File "/home/ec2-user/environment/test-tester/sqlalchemy/engine/__init__.py", line 500, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/ec2-user/environment/test-tester/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/ec2-user/environment/test-tester/sqlalchemy/dialects/sqlite/pysqlcipher.py", line 101, in dbapi
    raise e
  File "/home/ec2-user/environment/test-tester/sqlalchemy/dialects/sqlite/pysqlcipher.py", line 96, in dbapi
    from pysqlcipher import dbapi2 as sqlcipher
ModuleNotFoundError: No module named 'pysqlcipher'
```

**Comment by rhamnett** [comment]
@mccwdev I cannot get this to work on python3.8

I am installing pysqlcipher3 but when the code executes, it's trying to import pysqlcipher (not v3) as below.

```
{
  "errorMessage": "No module named 'pysqlcipher'",
  "errorType": "ModuleNotFoundError",
  "stackTrace": [
    "  File \"/var/task/index.py\", line 27, in handler\n    w = wallet_create_or_open('wlt-'+account_id, scheme='single', witness_type='segwit', db_uri='sqlite+pysqlcipher://:xxxxx@/mnt/wallet/crypt.db?cipher=aes-256-cfb&kdf_iter=64000')\n",
    "  File \"/opt/python/bitcoinlib/wallets.py\", line 117, in wallet_create_or_open\n    if wallet_exists(name, db_uri=db_uri):\n",
    "  File \"/opt/python/bitcoinlib/wallets.py\", line 99, in wallet_exists\n    if wallet in [x['name'] for x in wallets_list(db_uri)]:\n",
    "  File \"/opt/python/bitcoinlib/wallets.py\", line 67, in wallets_list\n    session = Db(db_uri=db_uri).session\n",
    "  File \"/opt/python/bitcoinlib/db.py\", line 67, in __init__\n    self.engine = create_engine(db_uri, isolation_level='READ UNCOMMITTED')\n",
    "  File \"/opt/python/sqlalchemy/engine/__init__.py\", line 500, in create_engine\n    return strategy.create(*args, **kwargs)\n",
    "  File \"/opt/python/sqlalchemy/engine/strategies.py\", line 87, in create\n    dbapi = dialect_cls.dbapi(**dbapi_args)\n",
    "  File \"/opt/python/sqlalchemy/dialects/sqlite/pysqlcipher.py\", line 101, in dbapi\n    raise e\n",
    "  File \"/opt/python/sqlalchemy/dialects/sqlite/pysqlcipher.py\", line 96, in dbapi\n    from pysqlcipher import dbapi2 as sqlcipher\n"
  ]
}
```

**Comment by mccwdev** [comment]
This issue seem related with the latest SQLAlchemy release. When I install an older version of SQLalchemy the pysqlcipher3 module works:
`pip install sqlalchemy==1.3.22`

**Comment by mccwdev** [comment]
Also see https://github.com/sqlalchemy/sqlalchemy/issues/5848

**Comment by rhamnett** [comment]
Hello @mccwdev - I have managed to successfully create an encrypted wallet with Wallet.create() as per the documentation link above. However wallet_create_or_open() function does not work despite just successfully creating a wallet prior.

```
  "errorMessage": "(pysqlcipher3.dbapi2.OperationalError) unable to open database file\n(Background on this error at: http://sqlalche.me/e/13/e3q8)",
```

Can you please check wallet_create_or_open() on your own setup? Thanks

**Comment by rhamnett** [comment]
Turns out I must have had an error in the DB connection string. Thanks for all your help. Seems to be working nicely.
