### ISSUE TITLE
private key zero padding: bitcoinlib.keys.BKeyError: Unrecognised key format

### ISSUE THREAD

**Issue by detvan** [1200wd/bitcoinlib#222]
Hello,

lets have 2 private keys for bitcoin:

```python
from bitcoinlib.keys import Key

private_key='000C2176BAE7EE8D499C3A2A0BB921714F6896C9EFD9FC6DC314A92C8B30FA15'
k = Key(private_key, is_private=True, compressed=False, network='bitcoin')
k.info()
```

Following program showing error, because of missing zero padding

```python
from bitcoinlib.keys import Key

private_key='C2176BAE7EE8D499C3A2A0BB921714F6896C9EFD9FC6DC314A92C8B30FA15'
k = Key(private_key, is_private=True, compressed=False, network='bitcoin')
k.info()
```
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/bitcoinlib/keys.py", line 747, in __init__
    kf = get_key_format(import_key)
  File "/home/user/.local/lib/python3.9/site-packages/bitcoinlib/keys.py", line 221, in get_key_format
    raise BKeyError("Unrecognised key format")
bitcoinlib.keys.BKeyError: Unrecognised key format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.9/site-packages/bitcoinlib/keys.py", line 750, in __init__
    raise BKeyError("Unrecognised key format")
bitcoinlib.keys.BKeyError: Unrecognised key format
```

Please could you add to this this very useful library option or feature for accepting/padding private keys in hex format shorter than 64 chars.

Something like:
```python
k = Key(private_key, pad=True, is_private=True, compressed=False, network='bitcoin')
```

Thank you very much in advance. I am pretty sure this feature will be useful also for another users. Your are doing great job!

**Comment by mccwdev** [comment]
The first attribute 'import_key' in Key can be in a lot of different forms (wif, private or public hex, decimal, etc). So the length is checked to avoid mixups of keys.

You could convert to an integer to be able to use shorter keys:
```
private_key = 'C2176BAE7EE8D499C3A2A0BB921714F6896C9EFD9FC6DC314A92C8B30FA15'
k = Key(int(private_key, 16), compressed=False)
k.info()
```

**Comment by detvan** [comment]
Thank you very much for nice tip.
