### ISSUE TITLE
Fails to parse specific transaction 

### ISSUE THREAD

**Issue by ravi-ojha** [1200wd/bitcoinlib#280]
The transaction in question: https://mempool.space/tx/fa9aab2e98b82d4731deee4e8c46840a0533ee47b9664e659bbab0419892fd11

Example code:

```python
from bitcoinlib.services.bitcoind import BitcoindClient

bdc = BitcoindClient(base_url=base_url)

txid = "fa9aab2e98b82d4731deee4e8c46840a0533ee47b9664e659bbab0419892fd11"
tx = bdc.gettransaction(txid)
```

The error

```python
Traceback (most recent call last):
  File "/home/ubuntu/pybitcoinlib/test.py", line 17, in <module>
    tx = bdc.gettransaction(t)
  File "/home/ubuntu/.pyenv/versions/txenv/lib/python3.9/site-packages/bitcoinlib/services/bitcoind.py", line 220, in gettransaction
    return self._parse_transaction(tx_raw)
  File "/home/ubuntu/.pyenv/versions/txenv/lib/python3.9/site-packages/bitcoinlib/services/bitcoind.py", line 188, in _parse_transaction
    t = Transaction.parse_hex(tx['hex'], strict=self.strict, network=self.network)
  File "/home/ubuntu/.pyenv/versions/txenv/lib/python3.9/site-packages/bitcoinlib/transactions.py", line 1527, in parse_hex
    return cls.parse_bytesio(BytesIO(bytes.fromhex(rawtx)), strict, network)
  File "/home/ubuntu/.pyenv/versions/txenv/lib/python3.9/site-packages/bitcoinlib/transactions.py", line 1482, in parse_bytesio
    s = Script.parse_bytes(varstr(witness), strict=strict)
  File "/home/ubuntu/.pyenv/versions/txenv/lib/python3.9/site-packages/bitcoinlib/scripts.py", line 468, in parse_bytes
    return cls.parse_bytesio(BytesIO(script), message, tx_data, strict, _level)
  File "/home/ubuntu/.pyenv/versions/txenv/lib/python3.9/site-packages/bitcoinlib/scripts.py", line 338, in parse_bytesio
    raise ScriptError(msg)
bitcoinlib.scripts.ScriptError: Malformed script, not enough data found
```

**Comment by mccwdev** [comment]
The transactions contains a non-standard script which cannot be parsed by default for security reasons.

You can parse it like this:
```
txid = 'fa9aab2e98b82d4731deee4e8c46840a0533ee47b9664e659bbab0419892fd11'
t = Service(providers=['bitcoind'], strict=False).gettransaction(txid)
```

**Comment by ravi-ojha** [comment]
Thanks! That was helpful. For those who stumble upon this, you'll have to also add `bitcoind` config in the providers.json

**Comment by ravi-ojha** [comment]
@mccwdev There issue still lingers.

```
from bitcoinlib.services.services import Service

txid = 'cc3afefe30dda8c31cbd39ad19efbdb14a28ac048d28fcf1cfc37c4bc424150b'
s = Service(providers=['bitcoind'], strict=True)

t = s.gettransaction(txid)
```

It logs the same error `Malformed script, not enough data found` but returns the Transaction object.

This Transaction object has some params missing or empty.

For eg: Notice that the `address` field is empty in the `inputs`

```
{'coinbase': False,
 'inputs': [<Input(prev_txid='b7243353f67cb799db171f21d1e8af045b5ec60babeab22a8bdc3c6813de8946', output_n=0, address='', index_n=0, type='sig_pubkey')>],
 'outputs': [<Output(value=2337, address=bc1qemqrchhnc336m70zm4ryn8jdcrmz596j0msagk5c7tt93wejwvvsz0gja0, type=p2wpkh)>],
 'version': b'\x00\x00\x00\x02',
 'version_int': 2,
 'locktime': 0,
 'network': <Network: bitcoin>,
 'flag': b'\x01',
 'fee': 163,
 'fee_per_kb': 1455,
 'size': 163,
 'vsize': 112,
 'txid': 'cc3afefe30dda8c31cbd39ad19efbdb14a28ac048d28fcf1cfc37c4bc424150b',
 'txhash': '',
 'date': datetime.datetime(2022, 12, 20, 13, 40, 1),
 'confirmations': 2,
 'block_height': 768220,
 'block_hash': '000000000000000000057c5fbaf55b31ed6e3f3c39a00b68e25a1dc9ce77af4a',
 'input_total': 2500,
 'output_total': 2337,
 'rawtx': b'\x02\x00\x00\x00\x00\x01\x01F\x89\xde\x13h<\xdc\x8b*\xb2\xea\xab\x0b\xc6^[\x04\xaf\xe8\xd1!\x1f\x17\xdb\x99\xb7|\xf6S3$\xb7\x00\x00\x00\x00\x00\xff\xff\xff\xff\x01!\t\x00\x00\x00\x00\x00\x00"\x00 \xce\xc0<^\xf3\xc4c\xad\xf9\xe2\xddFI\x9eM\xc0\xf6*\x17R~\xe1\xd4Z\x98\xf2\xd6X\xbb2s\x19\x01A\x11e\x0e\x81\xca\xbd\xbf\xac{g\xc5\xf0[c\xadBt\xdc\xcb\xe0\x9d\xec)\xe9\x989g"\x1c\x0b~+\x1eh\xcb\x101\xba$\x85\xd6\xed\x03\xda\xfa\xd3\x16\x03\xf5\xa5\xd0\xb8[\x19\xb9\xc2\x8f\xc4\xd0_\xfe\x00I9\x01\x00\x00\x00\x00',
 'status': 'confirmed',
 'verified': True,
 'witness_type': 'segwit',
 'change': 0}
```

**Comment by mccwdev** [comment]
Its not a bug perse, its just that not all transactions are supported / parsed by Bitcoinlib. Some transactions are not standard or contain unknowns scripts and give an error when you try to parse them in Bitcoinlib.

You can avoid errors by using the strict=False parameter. This way the transactions is still parsed even if not all scripts all understood:

```
rawtx = '020000...00000'
t = Transaction.parse_hex(rawtx, strict=False)
t.info()
```
