### ISSUE TITLE
connect to litecoin testnet full node

### ISSUE THREAD

**Issue by superggn** [1200wd/bitcoinlib#298]
I'm currently running a litecoin testnet's full node myself

I tried adding my node in bitcoinlib/data/providers.json

```
  "superggn.litecoin.testnet": {
    "provider": "superggn",
    "network": "litecoin_testnet",
    "client_class": "MyTestServer",
    "provider_coin_id": "",
    "url": "159.138.132.44:19332",
    "api_key": "",
    "priority": 10,
    "denominator": 100000000,
    "network_overrides": null
  },
```
Then I tried re-enter the terminal, but I still got this error as if bitcoinlib is not querying my node
```
>>> from bitcoinlib.wallets import Service
>>> srv = Service(network='litecoin_testnet')
>>> fee = srv.estimatefee(2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gaoguannan/envs/litecoin/lib/python3.8/site-packages/bitcoinlib/services/services.py", line 465, in estimatefee
    fee = self._provider_execute('estimatefee', blocks)
  File "/Users/gaoguannan/envs/litecoin/lib/python3.8/site-packages/bitcoinlib/services/services.py", line 224, in _provider_execute
    raise ServiceError("No successful response from any serviceprovider: %s" % list(self.providers.keys()))
bitcoinlib.services.services.ServiceError: No successful response from any serviceprovider: ['bitaps.litecoin.testnet']
```

Question: 
1. Am I wrong in adding my litecoin testnet node? How to add a service provider? (third party or self hosted node)
2. Is adding service provider also feasible in other altcoins like dogecoin (testnet & mainnet)?

**Comment by mccwdev** [comment]
I think you need to use litecoind as provider and LitecoindClient as client. And the rpc username / password in the url:
```
  "litecoin.testnet": {
    "provider": "litecoind",
    "network": "litecoin_testnet",
    "client_class": "LitecoindClient",
    "provider_coin_id": "",
    "url": "http://user:password@159.138.132.44:19332",
    "api_key": "",
    "priority": 10,
    "denominator": 100000000,
    "network_overrides": null
  },
```

The server and txindex option in the litecoind configuration have to be enabled to make it more useful. Also see https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.setup-bitcoind-connection.html

**Comment by superggn** [comment]
Thanks!!! trying it out...

**Comment by superggn** [comment]
Hi mccwdev, I read the docs you mentioned, and successfully connect to my testnet node via LitecoindClient and to third party node via providers.json! Huge thanks!

Meanwhile I still got issue using `LitecoindClient` to connect with my third-party node
(I think modifying the providers.json is kind of easily forgotten when upgrading years later, so I'm looking for a way to connect without modifying the lib's code)


Here's how I connect to my own litecoin testnet node:
```python
from bitcoinlib.services.litecoind import LitecoindClient
base_url = 'http://test:test@159.123.123.99:19332'
ldc = LitecoindClient(base_url=base_url)
txid = '9a509c68d230eda1e2dde539b47ae55db673af8df2dd3cb330d13c962d24dcb5'
t = ldc.gettransaction(txid)
print(t)
```

Here's what I added to my `python3.8/site-packages/bitcoinlib/data/providers.json` (I use getblock.io as my third party node, on mainnet):
```
  "litecoin": {
    "provider": "litecoind",
    "network": "litecoin",
    "client_class": "LitecoindClient",
    "provider_coin_id": "",
    "url": "https://ltc.getblock.io/39e5b219-1c6f-4ad2-8a59-9484c314c782/mainnet/",
    "api_key": "",
    "priority": 10,
    "denominator": 100000000,
    "network_overrides": null
  },
```
Here's how I test if the connection is good
```python
from bitcoinlib.wallets import Service
# yes the third-party node is on mainnet
NETWORK = 'litecoin'
query_address = 'LajyQBeZaBA1NkZDeY8YT5RYYVRkXMvb2T'
utxos = Service(network=NETWORK).getutxos(query_address)
print(utxos)
```

But when I tried to connect to use the `LitecoindClient` way to connect to my getblock.io node, I got error:
```
>>> from bitcoinlib.services.litecoind import LitecoindClient
>>> base_url = 'https://ltc.getblock.io/39e5b219-1c6f-4ad2-8a59-9484c314c782/mainnet/'
>>> ldc = LitecoindClient(base_url=base_url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gaoguannan/envs/litecoin/lib/python3.8/site-packages/bitcoinlib/services/litecoind.py", line 142, in __init__
    self.proxy = AuthServiceProxy(base_url)
  File "/Users/gaoguannan/envs/litecoin/lib/python3.8/site-packages/bitcoinlib/services/authproxy.py", line 101, in __init__
    authpair = user + b':' + passwd
TypeError: unsupported operand type(s) for +: 'NoneType' and 'bytes'
```
Then I made some change to my base_url, still not good
```python
base_url = 'https://:@ltc.getblock.io/39e5b219-1c6f-4ad2-8a59-9484c314c782/mainnet/:9332'
base_url = 'https://:@ltc.getblock.io/39e5b219-1c6f-4ad2-8a59-9484c314c782/mainnet/:443'
base_url = 'https://:@ltc.getblock.io/39e5b219-1c6f-4ad2-8a59-9484c314c782/mainnet/:80'
ldc = LitecoindClient(base_url=base_url)
# mainnet
query_address = 'LajyQBeZaBA1NkZDeY8YT5RYYVRkXMvb2T'
ldc.getutxos(query_address)
```

**My question**:
I wonder if the config in providers.json works, we should also be able to configure it via `LitecoindClient`? How can I do it?

**Comment by superggn** [comment]
I opened a new issue, so close this now
