### ISSUE TITLE
mempool.space broken starting release 0.6.11

### ISSUE THREAD

**Issue by reqlez** [1200wd/bitcoinlib#316]
Hello.

0.6.10 working as expected.

In 0.6.11, just doing a simple wallet scan ( BTC testnet ) using only the mempool.space provider:

Traceback (most recent call last):
File "/app/btcwinit.py", line 44, in <module>
w.scan()
File "/app/.py/bitcoinlib/wallets.py", line 1877, in scan
if self.scan_key(key):
^^^^^^^^^^^^^^^^^^
File "/app/.py/bitcoinlib/wallets.py", line 1800, in scan_key
n_new = self.transactions_update(key_id=key.key_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.py/bitcoinlib/wallets.py", line 3118, in transactions_update
txs += srv.gettransactions(address, limit=limit, after_txid=self.transaction_last(address))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.py/bitcoinlib/services/services.py", line 373, in gettransactions
txs = self._provider_execute('gettransactions', address, qry_after_txid.hex(),  limit)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.py/bitcoinlib/services/services.py", line 224, in _provider_execute
raise ServiceError("No successful response from any serviceprovider: %s" % list(self.providers.keys()))
bitcoinlib.services.services.ServiceError: No successful response from any serviceprovider: ['mempool.testnet']
ERROR: Error: Command failed: python btcwinit.py password
Traceback (most recent call last):
File "/app/btcwinit.py", line 44, in <module>
w.scan()
File "/app/.py/bitcoinlib/wallets.py", line 1877, in scan
if self.scan_key(key):
^^^^^^^^^^^^^^^^^^
File "/app/.py/bitcoinlib/wallets.py", line 1800, in scan_key
n_new = self.transactions_update(key_id=key.key_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.py/bitcoinlib/wallets.py", line 3118, in transactions_update
txs += srv.gettransactions(address, limit=limit, after_txid=self.transaction_last(address))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.py/bitcoinlib/services/services.py", line 373, in gettransactions
txs = self._provider_execute('gettransactions', address, qry_after_txid.hex(),  limit)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/.py/bitcoinlib/services/services.py", line 224, in _provider_execute
raise ServiceError("No successful response from any serviceprovider: %s" % list(self.providers.keys()))
bitcoinlib.services.services.ServiceError: No successful response from any serviceprovider: ['mempool.testnet']

**Comment by mccwdev** [comment]
I could not find any problems in version 0.6.11 and the Mempool provider, all checks seem to run without problem.

Can you check if you can find any specific errors in the logs?  Maybe the error was caused by Mempool rate limits?
