### ISSUE TITLE
Problem when try to sign p2pkh and p2wpkh

### ISSUE THREAD

**Issue by albertobsd** [1200wd/bitcoinlib#332]
I am having some troubles when i try to make Transaction with two inputs (first p2pkh and second p2wpkh) thb i am not sure if i can do this.

legacy privakey comes from a paper wallet manully importe:

```
key_str_p2pkh = "WIF KEY HERE"
priv_p2pkh = Key(key_str_p2pkh, network=networkname, compressed=True)
```

segwith keys froms from an HDwallet
```
w = Wallet.create('TEST_KEY', keys=[hdk, hdk.public()], network=networkname,witness_type='segwit', db_uri=test_database, multisig=False)
path = f"m/84/0/0/0/0"
priv_p2wpkh = w.key_for_path(path)
```

inputs are manully constructed with some external API but basically is something like:

```
inputs = []
inputs.append( Input(prev_txid=uxto['txid'], output_n=uxto['vout'], keys=priv_p2pkh.public(), network=networkname) )
inputs.append( Input(prev_txid=uxto['txid'], output_n=uxto['vout'], keys=[hdk, hdk.public()], network=networkname, witness_type ='segwit') )
```

the Transaction is created here.
```
t = Transaction(inputs, [transaction_output], network=networkname) # A new TX
t.info()
```

The info output is:

```
Transaction bef28b961523252d9a6ebc0b6804772c69f1f9a6ee1512110051f1fb24f21a8b
Date: None
Network: testnet
Version: 1
Witness type: legacy
Status: new
Verified: False
Inputs
- mgXuMfAV4gmfmyagEpXKpPjsesqkhh9aqQ 0.00000000 tBTC c043bf01b98b584dd9ab933e2bc0c2c0d2ed076d10d1143cab2809eb744b3560 0
  legacy sig_pubkey; sigs: 0 (1-of-1) not validated
- tb1qnalqseczc2gurz3k5c5pcferlvh79rqgtjplp3 0.00000000 tBTC 92cfc68e55c9e8984a3b6ba49e7917d6c01dd235bf759447284c99bf6c2e869b 1
  segwit sig_pubkey; sigs: 0 (1-of-1) not validated
Outputs
- tb1qnalqseczc2gurz3k5c5pcferlvh79rqgtjplp3 0.00028031 tBTC p2wpkh U
Size: None
Vsize: None
Fee: None
Confirmations: None
Block: None
```

Up to here all seems good but when i try to make the signature:

```
t.sign(priv_p2pkh,index_n=0)
t.sign(hdk,index_n=1)
```

I get error

```
Traceback (most recent call last):
  File "wallet_bot.py", line 134, in <module>
    t.sign(hdk,index_n=1)
  File "/home/albertobsd/.local/lib/python3.8/site-packages/bitcoinlib/transactions.py", line 2205, in sign
    txid = self.signature_hash(tid, witness_type=self.inputs[tid].witness_type)
  File "/home/albertobsd/.local/lib/python3.8/site-packages/bitcoinlib/transactions.py", line 1964, in signature_hash
    return double_sha256(self.signature(sign_id, hash_type, witness_type), as_hex=as_hex)
  File "/home/albertobsd/.local/lib/python3.8/site-packages/bitcoinlib/transactions.py", line 1985, in signature
    return self.signature_segwit(sign_id, hash_type)
  File "/home/albertobsd/.local/lib/python3.8/site-packages/bitcoinlib/transactions.py", line 2000, in signature_segwit
    assert (self.witness_type == 'segwit')
AssertionError
```
if i change the hdk by priv_p2wpkh  i get this other
```
Traceback (most recent call last):
  File "wallet_bot.py", line 134, in <module>
    t.sign(priv_p2wpkh,index_n=index)
  File "/home/albertobsd/.local/lib/python3.8/site-packages/bitcoinlib/transactions.py", line 2190, in sign
    tid_keys = [k if isinstance(k, (HDKey, Key)) else Key(k, compressed=self.inputs[tid].compressed)
  File "/home/albertobsd/.local/lib/python3.8/site-packages/bitcoinlib/transactions.py", line 2190, in <listcomp>
    tid_keys = [k if isinstance(k, (HDKey, Key)) else Key(k, compressed=self.inputs[tid].compressed)
  File "/home/albertobsd/.local/lib/python3.8/site-packages/bitcoinlib/keys.py", line 780, in __init__
    kf = get_key_format(import_key)
  File "/home/albertobsd/.local/lib/python3.8/site-packages/bitcoinlib/keys.py", line 153, in get_key_format
    elif len(key) == 130 and key[:2] == '04' and not is_private:
TypeError: object of type 'WalletKey' has no len()
```

So at this point i don't know if i miss something or it is not possible at all?

Regards!

**Comment by mccwdev** [comment]
It seems the variable hdk is of the type HDWalletKey, you cannot use this to sign transactions.
You have to convert is to a HDKey or Key object first.

**Comment by albertobsd** [comment]
Finally i solve this...

First clue was:
assert (self.witness_type == 'segwit')

That means that the Transaction witness_type  is currently 'legacy' because first input was legacy or I don't know what is the default value but I set the witness_type manually before each signature:

```
    icount = 0
    for utxo in utxos:
        t.witness_type = utxo['witness_type']
        t.sign(utxo['key'],icount) 
        icount += 1
```

Here `utxos` is an aux array/dictionary

This work well for some test, where `utxo['witness_type'] = 'legacy'` for the first value and `utxo['witness_type'] = 'segwit'` for the second value.
