### ISSUE TITLE
non-JSON HTTP response with '401 Unauthorized' from server

### ISSUE THREAD

**Issue by pputnik** [1200wd/bitcoinlib#333]
Looks like authentication was changed and does not work with bitcoin core 25,0.

I tried "Connect using config files" and "Connect using base_url argument" from [the doc](https://bitcoinlib.readthedocs.io/en/latest/source/_static/manuals.setup-bitcoind-connection.html), tried with both `rpcauth` and `rpcuser/rpcpassword`, neither works for me.

If I use `rpcauth` (generated by share/rpcauth/rpcauth.py as mentioned in the config comments), then the error is 

```
Traceback (most recent call last):
  File "/root/priv/btc_core/./block_parser.py", line 3, in <module>
    bdc = BitcoindClient.from_config('/mnt/bitcoin/bitcoin.conf')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bitcoinlib/services/bitcoind.py", line 115, in from_config
    url = "http://%s:%s@%s:%s" % (config.get('rpc', 'rpcuser'), config.get('rpc', 'rpcpassword'), server, port)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/configparser.py", line 808, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'rpcuser' in section: 'rpc'
```

If I use `rpcuser/rpcpassword` the error is 

```
Traceback (most recent call last):
  File "/root/priv/btc_core/./block_parser.py", line 8, in <module>
    rt = bdc.getrawtransaction(txid)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bitcoinlib/services/bitcoind.py", line 236, in getrawtransaction
    res = self.proxy.getrawtransaction(txid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bitcoinlib/services/authproxy.py", line 141, in __call__
    response = self._get_response()
               ^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.4/lib/python3.11/site-packages/bitcoinlib/services/authproxy.py", line 188, in _get_response
    raise JSONRPCException({
bitcoinlib.services.authproxy.JSONRPCException: -342: non-JSON HTTP response with '401 Unauthorized' from server
```

Could you advise, please?
bitcoinlib-0.6.11, installed by `pip install...`. The server is on localhost.

**Comment by pputnik** [comment]
I'm sorry, my mistake. For everyone else: first make sure you can `curl` your service successfully.
