### ISSUE TITLE
Problem while installing bitcoinlib

### ISSUE THREAD

**Issue by johnkanagawa** [1200wd/bitcoinlib#388]
Hello,
I'm on Termux and I get this error when i try to install bitcoinlib using pip install bitcoinlib : 
`Collecting bitcoinlib
  Using cached bitcoinlib-0.6.14-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: requests>=2.25.0 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from bitcoinlib) (2.31.0)
Collecting ecdsa>=0.17 (from bitcoinlib)
  Using cached ecdsa-0.18.0-py2.py3-none-any.whl.metadata (29 kB)
Collecting pycryptodome>=3.14.1 (from bitcoinlib)
  Using cached pycryptodome-3.20.0.tar.gz (4.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting SQLAlchemy>=2.0.0 (from bitcoinlib)
  Using cached SQLAlchemy-2.0.28-py3-none-any.whl.metadata (9.6 kB)
Collecting fastecdsa>=2.2.1 (from bitcoinlib)
  Using cached fastecdsa-2.3.2.tar.gz (47 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy>=1.22.0 (from bitcoinlib)
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error
 × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      Collecting patchelf>=0.11.0
        Using cached patchelf-0.17.2.1.tar.gz (167 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting ninja>=1.8.2
        Using cached ninja-1.11.1.1.tar.gz (132 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: patchelf, ninja
        Building wheel for patchelf (pyproject.toml): started
        Building wheel for patchelf (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
        × Building wheel for patchelf (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [11 lines of output]
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-eh1o_o0w/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
                cmkr = cmaker.CMaker(cmake_executable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-eh1o_o0w/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 148, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-eh1o_o0w/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
                raise SKBuildError(msg) from err
            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for patchelf
        Building wheel for ninja (pyproject.toml): started
        Building wheel for ninja (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
        × Building wheel for ninja (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            /data/data/com.termux/files/usr/tmp/pip-build-env-kk1_4a8k/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output
              warnings.warn("git archive did not support describe output")
            /data/data/com.termux/files/usr/tmp/pip-build-env-kk1_4a8k/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied)
              warnings.warn("unprocessed git archival found (no export subst applied)")
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-kk1_4a8k/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
                cmkr = cmaker.CMaker(cmake_executable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-kk1_4a8k/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 148, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-kk1_4a8k/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
                raise SKBuildError(msg) from err
            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for ninja
      Failed to build patchelf ninja
      ERROR: Could not build wheels for patchelf, ninja, which is required to install pyproject.toml-based projects
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.`

Can someone help me ?

**Comment by mccwdev** [comment]
It looks like the installations fails on the numpy package. 

Maybe you try to install this package separately and see if you get any more specific errors.
