### ISSUE TITLE
bitcoinlib.scripts.ScriptError: Expected a sequence of 69 bytes, got 70

### ISSUE THREAD

**Issue by heyanlong** [1200wd/bitcoinlib#400]
```
block_conn.getblock(135106)
```

```
Traceback (most recent call last):
  File "/home/ec2-user/.virtualenvs/web3-btc/lib/python3.9/site-packages/bitcoinlib/scripts.py", line 345, in parse_bytesio
    sig = Signature.parse_bytes(data)
  File "/home/ec2-user/.virtualenvs/web3-btc/lib/python3.9/site-packages/bitcoinlib/keys.py", line 2003, in parse_bytes
    signature = convert_der_sig(signature[:-1], as_hex=False)
  File "/home/ec2-user/.virtualenvs/web3-btc/lib/python3.9/site-packages/bitcoinlib/encoding.py", line 457, in convert_der_sig
    r, s = DEREncoder.decode_signature(bytes(signature))
  File "/home/ec2-user/.virtualenvs/web3-btc/lib64/python3.9/site-packages/fastecdsa/encoding/der.py", line 65, in decode_signature
    raise InvalidDerSignature("Expected a sequence of {} bytes, got {}".format(
fastecdsa.encoding.der.InvalidDerSignature: Expected a sequence of 69 bytes, got 70
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ec2-user/.virtualenvs/web3-btc/lib/python3.9/site-packages/bitcoinlib/scripts.py", line 351, in parse_bytesio
    raise ScriptError(str(e))
bitcoinlib.scripts.ScriptError: Expected a sequence of 69 bytes, got 70
python-BaseException
```

**Comment by mccwdev** [comment]
This code works for me:

```
srv = Service()
b = srv.getblock(135106)
print(b)
```

You could also try to add the strict=False option:

```
srv = Service(strict=False)
b = srv.getblock(135106)
print(b)
```

**Comment by heyanlong** [comment]
So, what is `Service`?

**Comment by mccwdev** [comment]
Sorry, I forgot the include

```
from bitcoinlib.services.services import Service
```
