### ISSUE TITLE
unable to run after upgrade

### ISSUE THREAD

**Issue by rcastag** [1200wd/bitcoinlib#90]
I am getting a KeyError: 'prefix_bech32' 
Whenever I do anything other than --list-wallets

Command Line Wallet for BitcoinLib

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bitcoinlib/tools/cli_wallet.py", line 413, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/bitcoinlib/tools/cli_wallet.py", line 273, in main
    wlt = HDWallet(args.wallet_name, databasefile=databasefile)
  File "/usr/local/lib/python3.7/site-packages/bitcoinlib/wallets.py", line 1233, in __init__
    self.network = Network(db_wlt.network_name)
  File "/usr/local/lib/python3.7/site-packages/bitcoinlib/networks.py", line 227, in __init__
    self.prefix_bech32 = NETWORK_DEFINITIONS[network_name]['prefix_bech32']
KeyError: 'prefix_bech32'

**Comment by rcastag** [comment]
removed install log as @mccwdev  recommended in https://github.com/1200wd/bitcoinlib/issues/50
